import { randomUUID } from "node:crypto";

import type { Prisma } from "@prisma/client";

import { audit } from "./audit";
import { loadActiveBreakWindows } from "./break-windows";
import { HttpError } from "./http";
import { cancelProductionPlanPlannedMovements } from "./inventory-ledger";
import { refreshCumulativeMaterialRequirements } from "./material-forecast";
import { aggregateMonthlySuggestions } from "./monthly-production-schedule";
import {
  simulateMonthlyShiftSchedule,
  type SimulatedProductionPlan,
  type ShiftSimulationSkippedItem,
} from "./monthly-shift-simulation";
import { recalculateProductionPlan } from "./plan-engine";
import { PLANNED_PRODUCTION_PLAN_STATUSES } from "./plan-status";
import { prisma } from "./prisma";
import {
  loadMonthlyProductionSchedulePreview,
  MONTHLY_SHIFT_GENERATED_NOTE_PREFIX,
  type MonthlyProductionPlanningBasis,
} from "./product-planning-service";
import { diffMinutes } from "./time";
import { ceilDisplayQuantity } from "./units";

type MonthlyPlanningClient = typeof prisma | Prisma.TransactionClient;

export type MonthlyPlanningRunCreateInput = {
  dateFrom: string;
  dateTo: string;
  productionLeadDays?: number;
  planningBasis?: MonthlyProductionPlanningBasis;
  defaultStartTime?: string;
  baselineEndTime?: string;
  replaceExistingDrafts?: boolean;
  replaceGeneratedDraftsOnly?: boolean;
  generatedById?: string | null;
};

export type MonthlyPlanningRunAdoptInput = {
  adoptedById?: string | null;
  replaceExistingDrafts?: boolean;
  replaceGeneratedDraftsOnly?: boolean;
};

type CandidateScheduleMetadata = {
  version: 1;
  startTime: string;
  endTime: string;
  breakMinutes: number;
  peopleCount: number;
  assignedEmployees: { employeeId: string; employeeName: string }[];
  dueDates: string[];
  reasons: string[];
  warnings: string[];
  unit: string;
  productionType: "stock" | "make_to_order";
  productCode: string;
  productName: string;
  workAreaName: string;
  baselineEndTime: string;
};

type PlanningRunSourceSnapshot = {
  source: "monthly-schedule";
  dateFrom: string;
  dateTo: string;
  productionLeadDays: number;
  planningBasis: MonthlyProductionPlanningBasis;
  defaultStartTime: string;
  baselineEndTime: string;
  replaceExistingDrafts: boolean;
  replaceGeneratedDraftsOnly: boolean;
};

export async function createMonthlyPlanningRunFromSchedule(input: MonthlyPlanningRunCreateInput) {
  const dateFrom = new Date(input.dateFrom);
  const dateTo = new Date(input.dateTo);
  const productionLeadDays = input.productionLeadDays ?? 1;
  const planningBasis = input.planningBasis ?? "historical_actual";
  const defaultStartTime = input.defaultStartTime ?? "09:00";
  const baselineEndTime = input.baselineEndTime ?? "17:00";
  const replaceExistingDrafts = input.replaceExistingDrafts ?? false;
  const replaceGeneratedDraftsOnly = replaceExistingDrafts && (input.replaceGeneratedDraftsOnly ?? false);
  const yearMonth = input.dateFrom.slice(0, 7);

  const sourceSnapshot: PlanningRunSourceSnapshot = {
    source: "monthly-schedule",
    dateFrom: input.dateFrom,
    dateTo: input.dateTo,
    productionLeadDays,
    planningBasis,
    defaultStartTime,
    baselineEndTime,
    replaceExistingDrafts,
    replaceGeneratedDraftsOnly,
  };

  const preview = await loadMonthlyProductionSchedulePreview({
    dateFrom,
    dateTo,
    productionLeadDays,
    planningBasis,
    existingPlanStatuses: replaceGeneratedDraftsOnly
      ? [...PLANNED_PRODUCTION_PLAN_STATUSES]
      : replaceExistingDrafts
        ? ["tentative_confirmed", "confirmed"]
        : [...PLANNED_PRODUCTION_PLAN_STATUSES],
    excludeAutoGeneratedDrafts: replaceGeneratedDraftsOnly,
  });
  const items = aggregateMonthlySuggestions(preview.suggestions);

  const productIds = [...new Set(items.map((item) => item.productId))];
  const [products, shifts, existingPlans, existingAssignments, breakWindows, replacementTargets] =
    await Promise.all([
      loadProductsForSchedule(productIds),
      prisma.shift.findMany({
        where: {
          date: { gte: dateFrom, lte: dateTo },
          status: { not: "off" },
          employee: { active: true },
        },
        include: { employee: true },
        orderBy: [{ date: "asc" }, { startTime: "asc" }, { employee: { name: "asc" } }],
      }),
      prisma.productionPlan.findMany({
        where: {
          date: { gte: dateFrom, lte: dateTo },
          status: replaceGeneratedDraftsOnly
            ? { in: ["draft", "tentative_confirmed", "confirmed", "completed"] }
            : replaceExistingDrafts
              ? { in: ["tentative_confirmed", "confirmed", "completed"] }
              : { in: ["draft", "tentative_confirmed", "confirmed", "completed"] },
          ...(replaceGeneratedDraftsOnly
            ? {
                NOT: {
                  AND: [
                    { status: "draft" },
                    generatedPlanSelector(),
                  ],
                },
              }
            : {}),
        },
        select: {
          id: true,
          date: true,
          workAreaId: true,
          plannedStartTime: true,
          plannedEndTime: true,
        },
        orderBy: [{ date: "asc" }, { plannedStartTime: "asc" }],
      }),
      prisma.productionPlanAssignment.findMany({
        where: {
          productionPlan: {
            date: { gte: dateFrom, lte: dateTo },
            status: replaceGeneratedDraftsOnly
              ? { in: ["draft", "tentative_confirmed", "confirmed", "completed"] }
              : replaceExistingDrafts
                ? { in: ["tentative_confirmed", "confirmed", "completed"] }
                : { in: ["draft", "tentative_confirmed", "confirmed", "completed"] },
            ...(replaceGeneratedDraftsOnly
              ? {
                  NOT: {
                    AND: [
                      { status: "draft" },
                      generatedPlanSelector(),
                    ],
                  },
                }
              : {}),
          },
        },
        include: { productionPlan: true },
      }),
      loadActiveBreakWindows(dateFrom),
      loadReplaceablePlans(prisma, {
        dateFrom,
        dateTo,
        replaceExistingDrafts,
        replaceGeneratedDraftsOnly,
      }),
    ]);

  const simulation =
    items.length === 0
      ? { plans: [] as SimulatedProductionPlan[], skipped: [] as ShiftSimulationSkippedItem[] }
      : simulateMonthlyShiftSchedule({
          dateFrom: input.dateFrom,
          dateTo: input.dateTo,
          defaultStartTime,
          baselineEndTime,
          items: items.map((item) => ({
            productId: item.productId,
            productCode: item.productCode,
            productName: item.productName,
            productionType: item.productionType,
            unit: item.unit,
            preferredDate: item.scheduleDate,
            dueDates: item.dueDates,
            quantity: item.suggestedQuantity,
            schedulePriority: item.schedulePriority,
            reasons: item.reasons,
          })),
          products: products.map((product) => ({
            productId: product.id,
            productCode: product.productCode,
            productName: product.officialName,
            productionType: product.productionType as "stock" | "make_to_order" | "both",
            unit: product.unit,
            defaultWorkAreaId: product.defaultWorkAreaId,
            capacities: product.capacities
              .filter(
                (capacity) =>
                  capacity.workArea.active &&
                  capacity.workArea.areaType === "internal" &&
                  !capacity.workArea.externalFlag,
              )
              .map((capacity) => ({
                productId: product.id,
                workAreaId: capacity.workAreaId,
                workAreaName: capacity.workArea.name,
                workAreaDefaultStartTime: capacity.workArea.defaultStartTime,
                workAreaDefaultEndTime: capacity.workArea.defaultEndTime,
                workAreaMaxPeopleCount: capacity.workArea.maxPeopleCount,
                workAreaDisplayOrder: capacity.workArea.displayOrder,
                workAreaAutoScheduleRole: capacity.workArea.autoScheduleRole,
                unitsPerPersonHour: capacity.unitsPerPersonHour,
                standardPeople: capacity.standardPeople,
                standardBreakMinutes: capacity.standardBreakMinutes,
                candidatePriority: capacity.candidatePriority,
              })),
          })),
          shifts: shifts.map((shift) => ({
            employeeId: shift.employeeId,
            employeeName: shift.employee.name,
            date: toDateInput(shift.date),
            startTime: shift.startTime,
            endTime: shift.endTime,
          })),
          existingPlans: existingPlans.map((plan) => ({
            date: toDateInput(plan.date),
            workAreaId: plan.workAreaId,
            startTime: plan.plannedStartTime,
            endTime: plan.plannedEndTime ?? plan.plannedStartTime,
          })),
          existingAssignments: existingAssignments.map((assignment) => ({
            employeeId: assignment.employeeId,
            date: toDateInput(assignment.productionPlan.date),
            startTime: assignment.startTime,
            endTime: assignment.endTime,
          })),
          breakWindows,
        });

  const replacementIdsByCandidateKey = assignReplacementIds(simulation.plans, replacementTargets);
  const totalEstimatedMinutes = simulation.plans.reduce(
    (sum, plan) => sum + Math.max(0, diffMinutes(plan.startTime, plan.endTime)),
    0,
  );
  const assignedPeopleTotal = simulation.plans.reduce((sum, plan) => sum + plan.assignedEmployees.length, 0);

  const run = await prisma.$transaction(async (tx) => {
    const createdRun = await tx.monthlyPlanningRun.create({
      data: {
        yearMonth,
        status: "simulated",
        basis: planningBasis,
        generatedById: input.generatedById ?? null,
        sourceSnapshotJson: JSON.stringify(sourceSnapshot),
        capacitySummaryJson: JSON.stringify({
          candidateCount: simulation.plans.length,
          skippedCount: simulation.skipped.length,
          totalEstimatedMinutes,
          assignedPeopleTotal,
          defaultStartTime,
          baselineEndTime,
        }),
        demandSummaryJson: JSON.stringify({
          suggestionCount: preview.suggestions.length,
          groupedSuggestionCount: items.length,
          productSummaryCount: preview.productSummaries.length,
          planningBasis,
        }),
        materialForecastSnapshotJson: JSON.stringify({
          status: "not_evaluated",
          note: "Candidates are evaluated against materials after adoption when ProductionPlan requirements are calculated.",
        }),
      },
    });

    if (simulation.plans.length > 0) {
      await tx.productionPlanCandidate.createMany({
        data: simulation.plans.map((simulated, index) => {
          const quantity = ceilDisplayQuantity(simulated.quantity) ?? 0;
          const metadata: CandidateScheduleMetadata = {
            version: 1,
            startTime: simulated.startTime,
            endTime: simulated.endTime,
            breakMinutes: simulated.breakMinutes,
            peopleCount: simulated.peopleCount,
            assignedEmployees: simulated.assignedEmployees,
            dueDates: simulated.dueDates,
            reasons: simulated.reasons,
            warnings: simulated.warnings,
            unit: simulated.unit,
            productionType: simulated.productionType,
            productCode: simulated.productCode,
            productName: simulated.productName,
            workAreaName: simulated.workAreaName,
            baselineEndTime,
          };

          return {
            planningRunId: createdRun.id,
            productId: simulated.productId,
            planDate: new Date(simulated.date),
            quantity,
            workAreaId: simulated.workAreaId,
            roomId: null,
            demandType: demandTypeFor(simulated.productionType, planningBasis),
            priority: index + 1,
            estimatedMinutes: Math.max(0, diffMinutes(simulated.startTime, simulated.endTime)),
            capacityReason: JSON.stringify(metadata),
            materialRisk: materialRiskFor(simulated.warnings),
            sourceDemandIdsJson: "[]",
            replacesPlanId: replacementIdsByCandidateKey.get(candidateKey(simulated)) ?? null,
          };
        }),
      });
    }

    await audit(
      {
        action: "monthly_planning_run_create",
        entityType: "MonthlyPlanningRun",
        entityId: createdRun.id,
        after: {
          runId: createdRun.id,
          yearMonth,
          candidateCount: simulation.plans.length,
          skipped: simulation.skipped,
          options: sourceSnapshot,
        },
      },
      tx,
    );

    return createdRun;
  });

  const candidates = await loadCandidateSummaries(run.id);
  return {
    run,
    candidates,
    skipped: simulation.skipped,
    sourceSnapshot,
    message:
      simulation.skipped.length > 0
        ? `${candidates.length}件の月間計画候補を保存しました。${simulation.skipped.length}件は未配置です。`
        : candidates.length > 0
          ? `${candidates.length}件の月間計画候補を保存しました。`
          : planningBasis === "historical_actual"
            ? "前々月前年比予測と既存予定を見た結果、追加の月間生産候補は不要です。"
            : "現在庫、未処理需要、既存予定を見た結果、追加の月間生産候補は不要です。",
  };
}

export async function listMonthlyPlanningRuns(params: {
  yearMonth?: string | null;
  limit?: number;
}) {
  const runs = await prisma.monthlyPlanningRun.findMany({
    where: {
      ...(params.yearMonth ? { yearMonth: params.yearMonth } : {}),
    },
    include: {
      _count: { select: { candidates: true, productionPlans: true, batches: true } },
      batches: { orderBy: { adoptedAt: "desc" }, take: 1 },
    },
    orderBy: [{ generatedAt: "desc" }, { id: "desc" }],
    take: params.limit ?? 20,
  });

  return runs.map((run) => ({
    id: run.id,
    yearMonth: run.yearMonth,
    status: run.status,
    basis: run.basis,
    generatedAt: run.generatedAt.toISOString(),
    adoptedAt: run.adoptedAt?.toISOString() ?? null,
    candidateCount: run._count.candidates,
    productionPlanCount: run._count.productionPlans,
    batchCount: run._count.batches,
    latestBatchId: run.batches[0]?.id ?? null,
  }));
}

export async function getMonthlyPlanningRunPreview(runId: string) {
  const run = await prisma.monthlyPlanningRun.findUnique({
    where: { id: runId },
    include: {
      candidates: {
        include: { product: true, workArea: true, replacesPlan: true },
        orderBy: [{ planDate: "asc" }, { priority: "asc" }, { id: "asc" }],
      },
      batches: { orderBy: [{ adoptedAt: "desc" }, { id: "desc" }] },
    },
  });
  if (!run) throw new HttpError(404, "monthly_planning_run_not_found");

  const source = parseSourceSnapshot(run.sourceSnapshotJson);
  const range = rangeForRun(run, source);
  const existingPlans = await prisma.productionPlan.findMany({
    where: {
      date: { gte: range.dateFrom, lte: range.dateTo },
      status: { in: ["draft", "tentative_confirmed", "confirmed", "completed"] },
    },
    include: { product: true, workArea: true, productDemands: { select: { id: true } } },
    orderBy: [{ date: "asc" }, { plannedStartTime: "asc" }, { id: "asc" }],
  });

  const existingByExactKey = new Map<string, typeof existingPlans>();
  for (const plan of existingPlans) {
    const rows = existingByExactKey.get(existingPlanExactKey(plan)) ?? [];
    rows.push(plan);
    existingByExactKey.set(existingPlanExactKey(plan), rows);
  }

  const matchedExistingIds = new Set<string>();
  const candidateRows = run.candidates.map((candidate) => {
    const metadata = parseCandidateMetadata(candidate.capacityReason);
    const date = toDateInput(candidate.planDate);
    const exact = existingByExactKey.get(`${candidate.productId}:${date}:${candidate.workAreaId}`)?.[0];
    if (candidate.replacesPlanId) matchedExistingIds.add(candidate.replacesPlanId);
    if (exact) matchedExistingIds.add(exact.id);
    const diffType = candidate.replacesPlanId
      ? "replace"
      : exact && round4(exact.plannedQuantity) === round4(candidate.quantity)
        ? "unchanged"
        : exact
          ? "resize"
          : "add";

    return {
      id: candidate.id,
      planningRunId: candidate.planningRunId,
      productId: candidate.productId,
      productCode: candidate.product.productCode,
      productName: candidate.product.displayName || candidate.product.officialName,
      planDate: date,
      quantity: candidate.quantity,
      unit: metadata?.unit ?? candidate.product.unit,
      productionType: metadata?.productionType ?? productionTypeForProduct(candidate.product.productionType),
      workAreaId: candidate.workAreaId,
      workAreaName: candidate.workArea.name,
      startTime: metadata?.startTime ?? null,
      endTime: metadata?.endTime ?? null,
      breakMinutes: metadata?.breakMinutes ?? 0,
      peopleCount: metadata?.peopleCount ?? null,
      assignedEmployees: metadata?.assignedEmployees ?? [],
      demandType: candidate.demandType,
      priority: candidate.priority,
      estimatedMinutes: candidate.estimatedMinutes,
      materialRisk: candidate.materialRisk,
      sourceDemandIds: parseJsonArray(candidate.sourceDemandIdsJson),
      replacesPlanId: candidate.replacesPlanId,
      diffType,
      warnings: metadata?.warnings ?? [],
      reasons: metadata?.reasons ?? [],
    };
  });

  const deleteCandidates = existingPlans
    .filter((plan) => isReplaceablePlanRow(plan, source))
    .filter((plan) => !matchedExistingIds.has(plan.id))
    .map((plan) => ({
      id: plan.id,
      productId: plan.productId,
      productCode: plan.product.productCode,
      productName: plan.product.displayName || plan.product.officialName,
      planDate: toDateInput(plan.date),
      quantity: plan.plannedQuantity,
      unit: plan.unit,
      productionType: plan.productionType,
      workAreaId: plan.workAreaId,
      workAreaName: plan.workArea.name,
      status: plan.status,
      diffType: "delete_candidate" as const,
    }));

  const diffSummary = {
    add: candidateRows.filter((row) => row.diffType === "add").length,
    replace: candidateRows.filter((row) => row.diffType === "replace").length,
    resize: candidateRows.filter((row) => row.diffType === "resize").length,
    unchanged: candidateRows.filter((row) => row.diffType === "unchanged").length,
    deleteCandidate: deleteCandidates.length,
  };

  return {
    run: {
      id: run.id,
      yearMonth: run.yearMonth,
      status: run.status,
      basis: run.basis,
      generatedAt: run.generatedAt.toISOString(),
      adoptedAt: run.adoptedAt?.toISOString() ?? null,
      sourceSnapshot: source,
      capacitySummary: parseJsonObject(run.capacitySummaryJson),
      demandSummary: parseJsonObject(run.demandSummaryJson),
      materialForecastSnapshot: parseJsonObject(run.materialForecastSnapshotJson),
      batches: run.batches.map((batch) => ({
        id: batch.id,
        status: batch.status,
        adoptedAt: batch.adoptedAt?.toISOString() ?? null,
      })),
    },
    dateFrom: toDateInput(range.dateFrom),
    dateTo: toDateInput(range.dateTo),
    candidateCount: candidateRows.length,
    candidates: candidateRows,
    existingPlans: existingPlans.map((plan) => ({
      id: plan.id,
      productId: plan.productId,
      productCode: plan.product.productCode,
      productName: plan.product.displayName || plan.product.officialName,
      planDate: toDateInput(plan.date),
      startTime: plan.plannedStartTime,
      endTime: plan.plannedEndTime,
      quantity: plan.plannedQuantity,
      unit: plan.unit,
      productionType: plan.productionType,
      workAreaId: plan.workAreaId,
      workAreaName: plan.workArea.name,
      status: plan.status,
      planningRunId: plan.planningRunId,
      planningBatchId: plan.planningBatchId,
      linkedDemandCount: plan.productDemands.length,
    })),
    deleteCandidates,
    diffSummary,
    calendarEvents: [
      ...candidateRows.map((candidate) => ({
        id: candidate.id,
        kind: "candidate" as const,
        date: candidate.planDate,
        productId: candidate.productId,
        productName: candidate.productName,
        workAreaId: candidate.workAreaId,
        workAreaName: candidate.workAreaName,
        quantity: candidate.quantity,
        unit: candidate.unit,
        diffType: candidate.diffType,
      })),
      ...existingPlans.map((plan) => ({
        id: plan.id,
        kind: "existing_plan" as const,
        date: toDateInput(plan.date),
        productId: plan.productId,
        productName: plan.product.displayName || plan.product.officialName,
        workAreaId: plan.workAreaId,
        workAreaName: plan.workArea.name,
        quantity: plan.plannedQuantity,
        unit: plan.unit,
        status: plan.status,
      })),
    ],
  };
}

export async function adoptMonthlyPlanningRun(runId: string, input: MonthlyPlanningRunAdoptInput = {}) {
  const createdPlans: AdoptedPlanSummary[] = [];
  let replacedPlanCount = 0;
  let batchId = "";
  let dateToForRefresh: Date | null = null;
  let dateFromForRefresh: Date | null = null;

  await prisma.$transaction(
    async (tx) => {
      const claimed = await tx.monthlyPlanningRun.updateMany({
        where: { id: runId, status: "simulated", adoptedAt: null },
        data: { status: "adopted" },
      });
      if (claimed.count !== 1) {
        const existing = await tx.monthlyPlanningRun.findUnique({
          where: { id: runId },
          select: { id: true, status: true, adoptedAt: true },
        });
        if (!existing) throw new HttpError(404, "monthly_planning_run_not_found");
        throw new HttpError(409, "monthly_planning_run_already_adopted", {
          runId,
          status: existing.status,
        });
      }

      const run = await tx.monthlyPlanningRun.findUnique({
        where: { id: runId },
        include: {
          candidates: {
            include: { product: true, workArea: true },
            orderBy: [{ planDate: "asc" }, { priority: "asc" }, { id: "asc" }],
          },
          batches: { where: { status: "active" }, take: 1 },
        },
      });
      if (!run) throw new HttpError(404, "monthly_planning_run_not_found");
      if (run.batches.length > 0) {
        throw new HttpError(409, "monthly_planning_run_already_adopted", {
          runId,
          status: run.status,
        });
      }

      const source = parseSourceSnapshot(run.sourceSnapshotJson);
      const range = rangeForRun(run, source);
      dateFromForRefresh = range.dateFrom;
      dateToForRefresh = range.dateTo;
      const replaceExistingDrafts = input.replaceExistingDrafts ?? source?.replaceExistingDrafts ?? false;
      const replaceGeneratedDraftsOnly =
        replaceExistingDrafts && (input.replaceGeneratedDraftsOnly ?? source?.replaceGeneratedDraftsOnly ?? false);

      const replacementTargets = await loadReplaceablePlans(tx, {
        dateFrom: range.dateFrom,
        dateTo: range.dateTo,
        replaceExistingDrafts,
        replaceGeneratedDraftsOnly,
      });
      for (const plan of replacementTargets) {
        await cancelProductionPlanPlannedMovements(tx, plan.id);
      }
      if (replacementTargets.length > 0) {
        await tx.productionPlan.deleteMany({ where: { id: { in: replacementTargets.map((plan) => plan.id) } } });
      }
      replacedPlanCount = replacementTargets.length;

      const batch = await tx.productionPlanBatch.create({
        data: {
          planningRunId: run.id,
          status: "active",
          adoptedById: input.adoptedById ?? null,
          adoptedAt: new Date(),
        },
      });
      batchId = batch.id;

      const planRows = run.candidates.map((candidate) => {
        const metadata = parseCandidateMetadata(candidate.capacityReason);
        const planId = randomUUID();
        const productionType = metadata?.productionType ?? productionTypeForProduct(candidate.product.productionType);
        const unit = metadata?.unit ?? candidate.product.unit;
        const startTime = metadata?.startTime ?? "09:00";
        const endTime = metadata?.endTime ?? null;
        const baselineEndTime = metadata?.baselineEndTime ?? source?.baselineEndTime ?? "17:00";

        createdPlans.push({
          id: planId,
          candidateId: candidate.id,
          date: toDateInput(candidate.planDate),
          productCode: candidate.product.productCode,
          productName: candidate.product.displayName || candidate.product.officialName,
          workAreaName: candidate.workArea.name,
          startTime,
          endTime: endTime ?? startTime,
          quantity: candidate.quantity,
          unit,
          assignedCount: metadata?.assignedEmployees.length ?? 0,
          warnings: metadata?.warnings ?? [],
        });

        return {
          id: planId,
          candidate,
          metadata,
          data: {
            id: planId,
            date: candidate.planDate,
            productId: candidate.productId,
            productionType,
            plannedQuantity: candidate.quantity,
            unit,
            workAreaId: candidate.workAreaId,
            plannedStartTime: startTime,
            plannedEndTime: endTime,
            desiredEndTime: baselineEndTime,
            breakMinutes: metadata?.breakMinutes ?? 0,
            plannedPeopleCount: metadata?.peopleCount ?? 1,
            status: "draft",
            baselineEndTime,
            overtimeMinutes: 0,
            planningRunId: run.id,
            planningBatchId: batch.id,
            note: buildMonthlyNote(metadata?.dueDates ?? [], metadata?.reasons ?? [], metadata?.warnings ?? []),
          },
        };
      });

      if (planRows.length > 0) {
        await tx.productionPlan.createMany({ data: planRows.map((row) => row.data) });
        const assignmentRows = planRows.flatMap((row) =>
          (row.metadata?.assignedEmployees ?? []).map((employee) => ({
            productionPlanId: row.id,
            employeeId: employee.employeeId,
            startTime: row.metadata?.startTime ?? "09:00",
            endTime: row.metadata?.endTime ?? row.metadata?.startTime ?? "09:00",
          })),
        );
        if (assignmentRows.length > 0) await tx.productionPlanAssignment.createMany({ data: assignmentRows });
      }

      await tx.monthlyPlanningRun.update({
        where: { id: run.id },
        data: { adoptedAt: new Date() },
      });

      await audit(
        {
          action: "monthly_planning_run_adopt",
          entityType: "MonthlyPlanningRun",
          entityId: run.id,
          after: {
            runId: run.id,
            batchId: batch.id,
            createdPlanIds: createdPlans.map((plan) => plan.id),
            replacedPlanCount,
          },
        },
        tx,
      );
    },
    { timeout: 30_000 },
  );

  for (const plan of createdPlans) {
    await recalculateProductionPlan(plan.id, { refreshMaterialForecast: false });
  }

  if (createdPlans.length > 0 || replacedPlanCount > 0) {
    const dateFrom = minDate(startOfDay(dateFromForRefresh ?? new Date()), startOfDay(new Date()));
    const horizonEnd = new Date(dateToForRefresh ?? new Date());
    horizonEnd.setDate(horizonEnd.getDate() + 90);
    await refreshCumulativeMaterialRequirements({ dateFrom, dateTo: horizonEnd });
  }

  return {
    runId,
    batchId,
    createdCount: createdPlans.length,
    replacedPlanCount,
    plans: createdPlans,
    listUrl: `/production-plans?planningBatchId=${batchId}`,
    message:
      createdPlans.length > 0
        ? `${createdPlans.length}件の候補を仮予定として採用しました。`
        : replacedPlanCount > 0
          ? `${replacedPlanCount}件の置換対象を外し、空の月間計画batchを採用しました。`
          : "候補0件の月間計画runを採用しました。",
  };
}

type AdoptedPlanSummary = {
  id: string;
  candidateId: string;
  date: string;
  productCode: string;
  productName: string;
  workAreaName: string;
  startTime: string;
  endTime: string;
  quantity: number;
  unit: string;
  assignedCount: number;
  warnings: string[];
};

async function loadProductsForSchedule(productIds: string[]) {
  if (productIds.length === 0) return [];
  return prisma.product.findMany({
    where: { id: { in: productIds }, active: true },
    include: {
      capacities: {
        include: { workArea: true },
      },
    },
  });
}

async function loadCandidateSummaries(runId: string) {
  const candidates = await prisma.productionPlanCandidate.findMany({
    where: { planningRunId: runId },
    include: { product: true, workArea: true },
    orderBy: [{ planDate: "asc" }, { priority: "asc" }, { id: "asc" }],
  });

  return candidates.map((candidate) => {
    const metadata = parseCandidateMetadata(candidate.capacityReason);
    return {
      id: candidate.id,
      productId: candidate.productId,
      productCode: candidate.product.productCode,
      productName: candidate.product.displayName || candidate.product.officialName,
      date: toDateInput(candidate.planDate),
      planDate: toDateInput(candidate.planDate),
      workAreaId: candidate.workAreaId,
      workAreaName: candidate.workArea.name,
      startTime: metadata?.startTime ?? null,
      endTime: metadata?.endTime ?? null,
      quantity: candidate.quantity,
      unit: metadata?.unit ?? candidate.product.unit,
      assignedCount: metadata?.assignedEmployees.length ?? 0,
      warnings: metadata?.warnings ?? [],
      demandType: candidate.demandType,
      materialRisk: candidate.materialRisk,
      replacesPlanId: candidate.replacesPlanId,
    };
  });
}

async function loadReplaceablePlans(
  client: MonthlyPlanningClient,
  input: {
    dateFrom: Date;
    dateTo: Date;
    replaceExistingDrafts: boolean;
    replaceGeneratedDraftsOnly: boolean;
  },
) {
  if (!input.replaceExistingDrafts) return [];
  const rows = await client.productionPlan.findMany({
    where: {
      date: { gte: input.dateFrom, lte: input.dateTo },
      status: { in: ["draft", "tentative_confirmed"] },
      productionType: "stock",
      productDemands: { none: {} },
      ...(input.replaceGeneratedDraftsOnly ? generatedPlanSelector() : {}),
    },
    select: {
      id: true,
      productId: true,
      date: true,
      workAreaId: true,
      plannedQuantity: true,
      status: true,
      productionType: true,
      planningBatchId: true,
      note: true,
      dailyReport: { select: { id: true } },
      productDemands: { select: { id: true } },
    },
    orderBy: [{ date: "asc" }, { plannedStartTime: "asc" }, { id: "asc" }],
  });

  return rows.filter((row) => !row.dailyReport && row.productDemands.length === 0);
}

function assignReplacementIds(
  simulatedPlans: SimulatedProductionPlan[],
  replacementTargets: Awaited<ReturnType<typeof loadReplaceablePlans>>,
) {
  const targetsByKey = new Map<string, typeof replacementTargets>();
  for (const target of replacementTargets) {
    const key = `${target.productId}:${toDateInput(target.date)}:${target.workAreaId}`;
    const rows = targetsByKey.get(key) ?? [];
    rows.push(target);
    targetsByKey.set(key, rows);
  }

  const replacements = new Map<string, string>();
  for (const simulated of simulatedPlans) {
    const key = candidateKey(simulated);
    const rows = targetsByKey.get(key) ?? [];
    const replacement = rows.shift();
    if (replacement) replacements.set(key, replacement.id);
  }
  return replacements;
}

function generatedPlanSelector(): Prisma.ProductionPlanWhereInput {
  return {
    OR: [
      { planningBatchId: { not: null } },
      { note: { startsWith: MONTHLY_SHIFT_GENERATED_NOTE_PREFIX } },
    ],
  };
}

function isReplaceablePlanRow(
  plan: {
    status: string;
    productionType: string;
    planningBatchId: string | null;
    note: string | null;
    productDemands: { id: string }[];
  },
  source: PlanningRunSourceSnapshot | null,
) {
  if (!source?.replaceExistingDrafts) return false;
  if (!(plan.status === "draft" || plan.status === "tentative_confirmed")) return false;
  if (plan.productionType !== "stock") return false;
  if (plan.productDemands.length > 0) return false;
  if (!source.replaceGeneratedDraftsOnly) return true;
  return !!plan.planningBatchId || !!plan.note?.startsWith(MONTHLY_SHIFT_GENERATED_NOTE_PREFIX);
}

function candidateKey(plan: SimulatedProductionPlan) {
  return `${plan.productId}:${plan.date}:${plan.workAreaId}`;
}

function existingPlanExactKey(plan: { productId: string; date: Date; workAreaId: string }) {
  return `${plan.productId}:${toDateInput(plan.date)}:${plan.workAreaId}`;
}

function demandTypeFor(
  productionType: "stock" | "make_to_order",
  planningBasis: MonthlyProductionPlanningBasis,
) {
  if (productionType === "make_to_order") return "order";
  return planningBasis === "historical_actual" ? "forecast" : "inventory";
}

function materialRiskFor(warnings: string[]) {
  if (warnings.some((warning) => /不足|未登録/.test(warning))) return "needs_review";
  return "not_evaluated";
}

function productionTypeForProduct(productProductionType: string): "stock" | "make_to_order" {
  return productProductionType === "make_to_order" ? "make_to_order" : "stock";
}

function buildMonthlyNote(dueDates: string[], reasons: string[], warnings: string[]) {
  const uniqueDueDates = [...new Set(dueDates)].sort();
  const uniqueReasons = [...new Set(reasons)];
  const warningText = warnings.length > 0 ? ` / 注意: ${[...new Set(warnings)].join(", ")}` : "";
  return `${MONTHLY_SHIFT_GENERATED_NOTE_PREFIX} / 対象日: ${uniqueDueDates.join(", ")} / ${uniqueReasons.join(" / ")}${warningText}`;
}

function parseCandidateMetadata(value: string | null): CandidateScheduleMetadata | null {
  if (!value) return null;
  try {
    const parsed = JSON.parse(value) as Partial<CandidateScheduleMetadata>;
    if (parsed.version !== 1 || !parsed.startTime || !parsed.endTime) return null;
    return {
      version: 1,
      startTime: parsed.startTime,
      endTime: parsed.endTime,
      breakMinutes: parsed.breakMinutes ?? 0,
      peopleCount: parsed.peopleCount ?? 1,
      assignedEmployees: Array.isArray(parsed.assignedEmployees) ? parsed.assignedEmployees : [],
      dueDates: Array.isArray(parsed.dueDates) ? parsed.dueDates : [],
      reasons: Array.isArray(parsed.reasons) ? parsed.reasons : [],
      warnings: Array.isArray(parsed.warnings) ? parsed.warnings : [],
      unit: parsed.unit ?? "袋",
      productionType: parsed.productionType === "make_to_order" ? "make_to_order" : "stock",
      productCode: parsed.productCode ?? "",
      productName: parsed.productName ?? "",
      workAreaName: parsed.workAreaName ?? "",
      baselineEndTime: parsed.baselineEndTime ?? "17:00",
    };
  } catch {
    return null;
  }
}

function parseSourceSnapshot(value: string | null): PlanningRunSourceSnapshot | null {
  const parsed = parseJsonObject(value) as Partial<PlanningRunSourceSnapshot> | null;
  if (!parsed || parsed.source !== "monthly-schedule" || !parsed.dateFrom || !parsed.dateTo) return null;
  return {
    source: "monthly-schedule",
    dateFrom: parsed.dateFrom,
    dateTo: parsed.dateTo,
    productionLeadDays: parsed.productionLeadDays ?? 1,
    planningBasis:
      parsed.planningBasis === "inventory_shortage" ? "inventory_shortage" : "historical_actual",
    defaultStartTime: parsed.defaultStartTime ?? "09:00",
    baselineEndTime: parsed.baselineEndTime ?? "17:00",
    replaceExistingDrafts: parsed.replaceExistingDrafts ?? false,
    replaceGeneratedDraftsOnly: parsed.replaceGeneratedDraftsOnly ?? false,
  };
}

function parseJsonObject(value: string | null): Record<string, unknown> | null {
  if (!value) return null;
  try {
    const parsed = JSON.parse(value);
    return parsed && typeof parsed === "object" && !Array.isArray(parsed) ? parsed : null;
  } catch {
    return null;
  }
}

function parseJsonArray(value: string | null): unknown[] {
  if (!value) return [];
  try {
    const parsed = JSON.parse(value);
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

function rangeForRun(
  run: { yearMonth: string; candidates: { planDate: Date }[] },
  source: PlanningRunSourceSnapshot | null,
) {
  if (source) {
    return {
      dateFrom: new Date(source.dateFrom),
      dateTo: new Date(`${source.dateTo}T23:59:59.999Z`),
    };
  }
  if (run.candidates.length > 0) {
    return {
      dateFrom: startOfDay(minDateFromArray(run.candidates.map((candidate) => candidate.planDate))),
      dateTo: endOfDay(maxDateFromArray(run.candidates.map((candidate) => candidate.planDate))),
    };
  }
  const dateFrom = new Date(`${run.yearMonth}-01T00:00:00.000Z`);
  return { dateFrom, dateTo: endOfMonth(dateFrom) };
}

function toDateInput(date: Date) {
  return date.toISOString().slice(0, 10);
}

function startOfDay(date: Date) {
  return new Date(date.toISOString().slice(0, 10));
}

function endOfDay(date: Date) {
  return new Date(`${toDateInput(date)}T23:59:59.999Z`);
}

function endOfMonth(date: Date) {
  return new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth() + 1, 0, 23, 59, 59, 999));
}

function minDate(a: Date, b: Date) {
  return a < b ? a : b;
}

function minDateFromArray(dates: Date[]) {
  return new Date(Math.min(...dates.map((date) => date.getTime())));
}

function maxDateFromArray(dates: Date[]) {
  return new Date(Math.max(...dates.map((date) => date.getTime())));
}

function round4(value: number) {
  return Math.round(value * 10000) / 10000;
}
